export default{
    showAuthModal: false,
    showModalCourse: false,
    members: {} || null,
    token: sessionStorage.getItem('authtoken') || null,
    courseLists: [],
    topic: [],
    otpstatus: null,
    courseId: {},
    vocabularys: {},
    users: {} || null,
    courses: {} || null,
    topics: {} || null,
    vovcabs: {},
    allCourse: {},
    allTopics: {},
    allVocabs: {},
    totalRevenue: null,
    totalUsers: null,
    totalVips: null,
    totalCourses: null,
    totalVocabs: null,
    segments: null,
    months: null,
    listUsers: { content: [], page: {} },
    listCourses: { content: [], page: {} },
    listTopic: { content: [], page: {} },
    listVocab: { content: [], page: {} },
    voCabLearns: {},
    vocabLever: [],
    chartData: {},
    
} 